### ISSUE TITLE
Add sliver appbar

### ISSUE THREAD

**Issue by viveeeeeek** [viveeeeeek/1stHacktoberfest#102]
After implementing feature please attach screenshots of app with comments of PR

**Comment by t-bolt** [comment]
Hello @viveeeeeek.
I would like to work on this issue if it hasn't been solved already as the last assignee dropped interest in it.

**Comment by Nemo21** [comment]
Hello @viveeeeeek I would like to work on this issue if it is not resolved yet.

**Comment by Nemo21** [comment]
@viveeeeeek There seems to be an issue in the version. It shows the following bug. 
'> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 62'.

**Comment by Nemo21** [comment]
@viveeeeeek Dude, there seems to be not only issue with the version still but with the class extending as well, due to which now im stuck. Could you help?

**Comment by Perumallpardhiv** [comment]
@viveeeeeek pls review my pr and let me know if any changes required #114

**Comment by Perumallpardhiv** [comment]
@viveeeeeek pls review my pr #119 asap
I changed according to your feedback of pr #114

**Comment by Perumallpardhiv** [comment]
@viveeeeeek pls check #119 pr
