### ISSUE TITLE
Update banner to Hacktoberfest 2022.

### ISSUE THREAD

**Issue by viveeeeeek** [viveeeeeek/1stHacktoberfest#107]
Change old banner images and add new updated Hacktoberfest 2022 banenr images.

Images to be changed are below:
![image](https://user-images.githubusercontent.com/64553247/193400697-0e784cb4-1140-4ffa-9abb-ed48a0432fd4.png)
![image](https://user-images.githubusercontent.com/64553247/193400706-078367ba-8acb-4522-92e2-80af8b40c0dd.png)

**Comment by rrsingh11** [comment]
Can you assign this issue to me @viveeeeeek ?
