### ISSUE TITLE
Change List View to Grid View.

### ISSUE THREAD

**Issue by viveeeeeek** [viveeeeeek/1stHacktoberfest#58]
Change this Listview to Gridview.
![image](https://user-images.githubusercontent.com/64553247/136690994-1039a7dd-3e7e-4a9a-ba58-52c6250fe67a.png)

**Comment by utkryuk** [comment]
Hey. I would like to work on the issue. Can you assign me?

**Comment by utkryuk** [comment]
Okay. Working on it then.

**Comment by DarkLordZeus** [comment]
HII BROTHER ..I WOULD LIKE TO WORK ON THIS...CAN YOU PLEASE ASSIGN THIS TO ME??
