### ISSUE TITLE
README.md improvement needed

### ISSUE THREAD

**Issue by viveeeeeek** [viveeeeeek/1stHacktoberfest#6]

**Comment by ssurbhi09** [comment]
Can you assign me

**Comment by ajinkyabodke** [comment]
Can you assign this issue to me,i would update it at the earliest.

**Comment by viveeeeeek** [comment]
> Can you assign me

sure, wait I'll assign you a new issue earlyas possible. till then you can contribute.

**Comment by ajinkyabodke** [comment]
Check pr #7

**Comment by viveeeeeek** [comment]
Thanks @ajinkyabodke
