### ISSUE TITLE
Implement Dark Mode 

### ISSUE THREAD

**Issue by viveeeeeek** [viveeeeeek/1stHacktoberfest#86]
Implement Dark Mode on detailed page

**Comment by AwsmAsim** [comment]
https://github.com/viveeeeeek/1stHacktoberfest/pull/87

**Comment by viveeeeeek** [comment]
Great work buddy👍🏼

**Comment by viveeeeeek** [comment]
Hello @AwsmAsim 
There are some deprecated methods being used in app. Can you please check them out?
![image](https://user-images.githubusercontent.com/64553247/137669016-a8e7c7d8-db19-499e-8a87-90f6e2d38316.png)
And "CONTRIBUTERS" texts don't change its colour  in dark mode.
![image](https://user-images.githubusercontent.com/64553247/137669116-87513489-48b7-4dc4-a1e8-cf11e3002395.png)
![image](https://user-images.githubusercontent.com/64553247/137669085-89118f66-6314-4361-ac81-6917ceb7a656.png)
Thank you.
